version: '3.8'

services:
  app:
    build: .
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - COMPULIFE_DOMAIN=compulifeapi.com
      - COMPULIFE_AUTH_ID=760903F14
      - REMOTE_IP=74.113.157.69
      - FRONTEND_URL=http://localhost:5000
    restart: unless-stopped 